/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bb;

import java.awt.Component;
import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author josia
 */
public class createElectionFunc extends javax.swing.JFrame {
    
    
    DefaultListModel LiztModel;
        

    /**
     * Creates new form createElectionFunc
     */
    public createElectionFunc() {
       
        initComponents();
        LiztModel = new DefaultListModel();
        demoList.setModel(LiztModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rankBtnGroup = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        majorPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        List<String> collegeWords = new ArrayList<String>();
        collegeWords.add("Engineering");
        collegeWords.add("Mathematics");
        collegeWords.add("Law");
        collegeWords.add("Medical");
        collegeWords.add("Arts");
        collegeWords.add("Physics");
        collegeWords.add("Social Work");
        StringSearchable searchCollege = new StringSearchable(collegeWords);
        CollegeCombo = new bb.AutocompleteJComboBox(searchCollege);
        collegePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        List<String> MajorWords = new ArrayList<String>();
        MajorWords.add("Electrical Engineering");
        MajorWords.add("Computer Engineering");
        MajorWords.add("Computer Science");
        MajorWords.add("Art History");
        MajorWords.add("Puppetry");
        MajorWords.add("Mechanical Engineering");
        MajorWords.add("English");
        MajorWords.add("Theater");
        MajorWords.add("Enviromental Science");
        MajorWords.add("Business");
        StringSearchable searchMajor = new StringSearchable(MajorWords);
        MajorCombo = new bb.AutocompleteJComboBox(searchMajor);
        demoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        demoList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        addDemoBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        confirmElectionBtn = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        dateField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        ecField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rankPanel = new javax.swing.JPanel();
        freshCheck = new javax.swing.JCheckBox();
        sophCheck = new javax.swing.JCheckBox();
        juniCheck = new javax.swing.JCheckBox();
        seniCheck = new javax.swing.JCheckBox();
        gradCheck = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        genderPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        maleCheck = new javax.swing.JCheckBox();
        femaCheck = new javax.swing.JCheckBox();
        otheCheck = new javax.swing.JCheckBox();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 500));
        setResizable(false);

        jLabel1.setText("Create Election");

        jLabel9.setText("College");

        javax.swing.GroupLayout majorPanelLayout = new javax.swing.GroupLayout(majorPanel);
        majorPanel.setLayout(majorPanelLayout);
        majorPanelLayout.setHorizontalGroup(
            majorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(majorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(majorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CollegeCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(majorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        majorPanelLayout.setVerticalGroup(
            majorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(majorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CollegeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setText("Major");

        demoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(demoList);

        jLabel5.setText("Selected Demographics");

        addDemoBtn.setText("Add");
        addDemoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDemoBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout demoPanelLayout = new javax.swing.GroupLayout(demoPanel);
        demoPanel.setLayout(demoPanelLayout);
        demoPanelLayout.setHorizontalGroup(
            demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demoPanelLayout.createSequentialGroup()
                        .addComponent(addDemoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        demoPanelLayout.setVerticalGroup(
            demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(demoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDemoBtn)
                    .addComponent(removeBtn)))
        );

        confirmElectionBtn.setText("confirm");
        confirmElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmElectionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout collegePanelLayout = new javax.swing.GroupLayout(collegePanel);
        collegePanel.setLayout(collegePanelLayout);
        collegePanelLayout.setHorizontalGroup(
            collegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collegePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MajorCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(collegePanelLayout.createSequentialGroup()
                        .addGroup(collegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(demoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collegePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        collegePanelLayout.setVerticalGroup(
            collegePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collegePanelLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MajorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(demoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmElectionBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Date");

        jLabel6.setText("EC ID");

        freshCheck.setText("Freshman");
        freshCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freshCheckActionPerformed(evt);
            }
        });

        sophCheck.setText("Sophmore");

        juniCheck.setText("Junior");

        seniCheck.setText("Senior");

        gradCheck.setText("Graduate");

        jLabel11.setText("Rank");

        jLabel8.setText("Gender");

        maleCheck.setText("Male");

        femaCheck.setText("Female");

        otheCheck.setText("Other");

        javax.swing.GroupLayout genderPanelLayout = new javax.swing.GroupLayout(genderPanel);
        genderPanel.setLayout(genderPanelLayout);
        genderPanelLayout.setHorizontalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otheCheck)
                    .addComponent(femaCheck)
                    .addComponent(maleCheck)
                    .addComponent(jLabel8))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        genderPanelLayout.setVerticalGroup(
            genderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderPanelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(16, 16, 16)
                .addComponent(maleCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otheCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rankPanelLayout = new javax.swing.GroupLayout(rankPanel);
        rankPanel.setLayout(rankPanelLayout);
        rankPanelLayout.setHorizontalGroup(
            rankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradCheck)
                    .addGroup(rankPanelLayout.createSequentialGroup()
                        .addGroup(rankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(freshCheck)
                            .addComponent(sophCheck)
                            .addComponent(juniCheck)
                            .addComponent(seniCheck)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(genderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rankPanelLayout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rankPanelLayout.setVerticalGroup(
            rankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankPanelLayout.createSequentialGroup()
                .addGroup(rankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rankPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freshCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sophCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(juniCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seniCheck))
                    .addComponent(genderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)))
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ecField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(dateField))
                .addGap(64, 64, 64))
            .addGroup(namePanelLayout.createSequentialGroup()
                .addComponent(rankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ecField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(rankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(majorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(collegePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(majorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(collegePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmElectionBtnActionPerformed
        // TODO add your handling code here:
        
        
        int check1 = 0;
        int check2 = 0;
        int check3 = 0;
        
        String ecOutput = "";
        String dateOutput = "";
        String nameOutput = "";
        
        if(ecField.getText().equals(""))
        {
            //Show error dialog
            
            JOptionPane.showMessageDialog(null,"EC field missing","NOTICE!",JOptionPane.INFORMATION_MESSAGE);
            
            //Erase output
            ecOutput = "";
        }
        else
        {
            check1 = 1;
            ecOutput += ecField.getText();
        }
        
        if(dateField.getText().equals(""))
        {
            //Show error dialog
            JOptionPane.showMessageDialog(null,"Date field missing","NOTICE!",JOptionPane.INFORMATION_MESSAGE);
            
            //Erase output
            dateOutput = "";
        }
        else
        {
            check2 = 1;
            dateOutput += dateField.getText();
        }
        
        if(nameField.getText().equals(""))
        {
            //Show error dialog
            JOptionPane.showMessageDialog(null,"Name field missing","NOTICE!",JOptionPane.INFORMATION_MESSAGE);
            //Erase output
            nameOutput = "";
        }
        else
        {
            check3 = 1;
            nameOutput += nameField.getText();
        }
        
        
        
        if(check1 == 1 && check2 == 1 && check3==1)
        {
            this.setVisible(false);
            new createElectionConfor(nameOutput,ecOutput,dateOutput).setVisible(true);
            
        }
        
    }//GEN-LAST:event_confirmElectionBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void freshCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freshCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freshCheckActionPerformed

    private void addDemoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDemoBtnActionPerformed
        // TODO add your handling code here:
        
        
        if(sophCheck.isSelected() && !LiztModel.contains("Sophmore"))
        {
           LiztModel.addElement("Sophmore");
        }
        
        
        if(freshCheck.isSelected() && !LiztModel.contains("Freshman"))
        {
            LiztModel.addElement("Freshman");
        }
        
        if(seniCheck.isSelected() && !LiztModel.contains("Senior"))
        {
            LiztModel.addElement("Senior");
        }
        
        if(juniCheck.isSelected() && !LiztModel.contains("Junior"))
        {
            LiztModel.addElement("Junior");
        }
        
        if(gradCheck.isSelected()&& !LiztModel.contains("Gradute"))
        {
            LiztModel.addElement("Graduate");
        }
        
        if(maleCheck.isSelected() && !LiztModel.contains("Male"))
        {
            LiztModel.addElement("Male");
        }
        
        if(femaCheck.isSelected() && !LiztModel.contains("Female"))
        {
            LiztModel.addElement("Female");
        }
        
        if(otheCheck.isSelected() && !LiztModel.contains("Other"))
        {
            LiztModel.addElement("Other");
        }
        
        //Stuff from list 
        
        
        if(!LiztModel.contains(CollegeCombo.getSelectedItem()))
        {
           LiztModel.addElement(CollegeCombo.getSelectedItem()); 
        }
        
        if(!LiztModel.contains(MajorCombo.getSelectedItem()))
        {
           LiztModel.addElement(MajorCombo.getSelectedItem()); 
        }
        
        
        //Stuff for remocve
        
        
        
        
        
    }//GEN-LAST:event_addDemoBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        if(!LiztModel.isEmpty())
        {
          LiztModel.remove(demoList.getSelectedIndex());  
        }
        
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createElectionFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createElectionFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createElectionFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createElectionFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                                    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bb.AutocompleteJComboBox CollegeCombo;
    private bb.AutocompleteJComboBox MajorCombo;
    private javax.swing.JButton addDemoBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel collegePanel;
    private javax.swing.JButton confirmElectionBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JList<String> demoList;
    private javax.swing.JPanel demoPanel;
    private javax.swing.JTextField ecField;
    private javax.swing.JCheckBox femaCheck;
    private javax.swing.JCheckBox freshCheck;
    private javax.swing.JPanel genderPanel;
    private javax.swing.JCheckBox gradCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox juniCheck;
    private javax.swing.JPanel majorPanel;
    private javax.swing.JCheckBox maleCheck;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel namePanel;
    private javax.swing.JCheckBox otheCheck;
    private javax.swing.ButtonGroup rankBtnGroup;
    private javax.swing.JPanel rankPanel;
    private javax.swing.JButton removeBtn;
    private javax.swing.JCheckBox seniCheck;
    private javax.swing.JCheckBox sophCheck;
    // End of variables declaration//GEN-END:variables
}
